#
#	NormalizeAndDiscoverNovelJunctions.sh
#	May 18th, 2017
#	dennis.kao@sickkids.ca
#	
#	Usage: input=input.txt sample=sample ./NormalizeAndDiscoverNovelJunctions.sh
#	OR     input=input.txt sample=sample mindread=10 threshold=0.5 transcript_model=gencode.txt ./NormalizeAndDiscoverNovelJunctions.sh
#
#	Input - file generated by SpliceJunctionDiscovery.py or rnaseq.splice_junction_discovery.pbs
#	Output - a single text file with junctions only seen in "sample" with a read count >= "minread" and a normalized read count > "threshold"
#
#	Runtime: <10 seconds on a modern day machine with input of ~22000 lines

beryl_home=~/tools/MendelianRNA-seq

echo "NormalizeAndDiscoverNovelJunctions.sh started running on $(date)"

#	Mandatory parameters
if [ -z "$input" ];
	then
		echo "ERROR - Specify the path to an input file with the format:" 
		echo "Gene	Type	Chrom	Start	End	NTimesSeen	NSamplesSeen	Samples:NSeen"
		echo "AL627309.1	BLAH	1	136903	136953	1	1	G34487:1"
		echo "NormalizeAndDiscoverNovelJunctions.sh finished running on $date"
		exit 1
fi

if [ -z "$sample" ];
	then
		echo "ERROR - Specify the name of the bam file you want to discover novel junctions in"
		echo "If your file is patient1.bam, then write sample=patient1"
		echo "NormalizeAndDiscoverNovelJunctions.sh finished running on $date"
		exit 2
fi

#	Optional parameters
if [ -z "$minread" ];
then
		minread=10
fi

if [ -z "$threshold" ];
then
		threshold=0.5
fi

transcript_model_arg='-transcript_model='$transcript_model

if [ -z "$transcript_model" ];
then
		transcript_model_arg=''
fi

inputFileName=`basename $input`
outputFilePath=`dirname $input`

#	Actual code
output="threshold"$threshold"_novel_"$sample"_norm_"$inputFileName

$beryl_home/Analysis/NormalizeSpliceJunctionValues.py $transcript_model_arg -splice_file=$input --normalize | grep $sample | grep -v '*' | awk "{ if (\$5 == 1 && \$4 >= $minread ) print \$0 }" | sed "s/:$sample//" | sed "s/:$sample//" | awk "{if (\$7 == \"Neither\" || \$9 > $threshold) print \$0}" | cut -f 1,3,4,7,8,9 > $outputFilePath/$output

echo "NormalizeAndDiscoverNovelJunctions.sh finished running on $(date)"
echo "Output: "$output