#!/bin/bash

#PBS -l walltime=10:00:00,nodes=1:ppn=4
#PBS -joe .
#PBS -d .
#PBS -l vmem=10g,mem=10g

home='/home/dennis.kao/tools/MendelianRNA-seq-DB'

if [ -z "$transcriptfile" ];
then
		transcriptfile=$home/gencode.comprehensive.splice.junctions.txt
fi

if [ -z "$processes" ];
then
		processes=4
fi

if [ -z "$genelist" ];
then
	genelist=$home/all-protein-coding-genes.list
fi

module load python/3.5.2
python3 $home/Analysis/AddJunctionsToDatabase.py --addGencodeWithFlanks -transcript_model=$transcriptfile
python3 $home/Analysis/AddJunctionsToDatabase.py --addBAM -gene_list=$genelist -processes=$processes
