#!/bin/bash

#PBS -l walltime=200:00:00,nodes=1:ppn=20
#PBS -joe .
#PBS -d .
#PBS -l vmem=50g,mem=50g

home='/home/dennis.kao/tools/MendelianRNA-seq-DB'

if [ -z "$transcriptFile" ];
then
		transcriptFile=$home/gencode.comprehensive.splice.junctions.txt
fi

if [ -z "$processes" ];
then
		processes=20
fi

module load python/3.5.2
python $home/Analysis/SpliceJunctionSummary.py --addGencodeWithFlanking -transcript_model=/home/dennis.kao/tools/MendelianRNA-seq-DB/gencode.comprehensive.splice.junctions.txt
python $home/Analysis/SpliceJunctionSummary.py --addBAM -gene_list=/home/dennis.kao/largeWork/gene-lists/all-protein-coding-genes.list -processes=20
