#!/bin/bash

#PBS -l walltime=20:00:00,nodes=1:ppn=40
#PBS -joe .
#PBS -d .
#PBS -l vmem=40g,mem=40g

home='/home/dennis.kao/tools/MendelianRNA-seq-DB'

if [ -z "$transcript_file" ];
then
	transcript_file=$home/all-protein-coding-genes-no-patches.list
fi

if [ -z "$processes" ];
then
		processes=40
fi

if [ -z "$bam_list" ];
then
	bam_list=bamlist.list
fi

module load python/3.5.2
python3 $home/Analysis/SpliceJunctionDiscovery.py -transcript_file=$transcript_file -bam_list=$bam_list -processes=$processes
