#!/bin/bash

#PBS -l walltime=10:00:00,nodes=1:ppn=1
#PBS -joe .
#PBS -d .
#PBS -l vmem=10g,mem=10g

beryl_home=~/tools/MendelianRNA-seq

name=`basename $gene_list | sed 's/gencode.v19.genes.filtered.group//'`
sjdOutput="All."$name".splicing.txt"

#	Optional parameters
if [ -z "$minread" ];
then
		minread=10
fi

if [ -z "$threshold" ];
then
		threshold=0.5
fi

transcript_model_arg='transcript_model='$transcript_model

if [ -z "$transcript_model" ];
then
		transcript_model_arg=""
fi

~/tools/MendelianRNA-seq/Analysis/SpliceJunctionDiscovery.sh $gene_list $bam_list
input=$sjdOutput sample=$sample minread=$minread threshold=$threshold $transcript_model_arg ~/tools/MendelianRNA-seq/Analysis/NormalizeAndDiscoverNovelJunctions.sh