#!/bin/bash

#PBS -l walltime=200:00:00,nodes=1:ppn=6
#PBS -joe .
#PBS -d .
#PBS -l vmem=50g,mem=50g

home='/home/dennis.kao/tools/MendelianRNA-seq-DB'
name=`basename $transcriptFile`
sjdOutput="All."$name".splicing.list"

if [ -z "$transcriptFile" ];
then
		transcriptFile=$home/gencode.comprehensive.splice.junctions.txt
fi

if [ -z "$processes" ];
then
		processes=20
fi

if [ -z "$bamList" ];
then
		bamList='bamlist.list'
fi

module load python/3.5.2
python $home/Analysis/SpliceJunctionSummary.py --addGencode --enableFlanking
python $home/Analysis/SpliceJunctionSummary.py --addBAM -gene_list=/home/dennis.kao/largeWork/gene-lists/all-protein-coding-genes.list -transcript_model=/home/dennis.kao/largeWork/gene-lists/all-protein-coding-genes-no-patches.list